### ISSUE TITLE
Terminating app due to uncaught exception 'NSRangeException'

### ISSUE THREAD

**Issue by saiedkia** [map-ir/ios-sdk-v2-map-demo#3]
hi
**Received error:**
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MGLMapView 0x7fc47d858600> for the key path "hidden" from <UIButton 0x7fc47d42b9a0> because it is not registered as an observer.'

**Regenerate:**
1- run app
2- tap on any section
3- tap on back button
4- tap on any other section

SDK version : 2.1.0 https://map.ir/mobile/ios/mapir-ios-v2.1.0-dynamic.zip

**Comment by Mr-Alirezaa** [comment]
This issue is going to get fixed with the upcoming release.
Thanks.
